---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - qemu-guest-agent
      - ufw
    state: present

- name: Enable qemu guest agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
